on: pull_request
name: lychee link Checker
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore lychee cache
        uses: actions/cache@v4
        id: restore-cache
        with:
          path: .lycheecache
          key: cache-lychee-${{ github.sha }}
          restore-keys: cache-lychee-

      - name: lychee Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2.4.1
        with:
          args: --accept '100..=103,200..=299,429' --cache-exclude-status '429, 500..502' --cache --max-cache-age 1d --verbose --no-progress .
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # - name: Save lychee cache
      #   uses: actions/cache/save@v4
      #   if: always()
      #   with:
      #     path: .lycheecache
      #     key: ${{ steps.restore-cache.outputs.cache-primary-key }}
