name: update MAINTAINER files cronjob

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: "00 20 1 * *"

jobs:
  updateMaintainers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2.3.1
        with:
          python-version: 3.8
      - uses: BSFishy/pip-action@v1
        with:
          requirements: project/requirements.txt
      - run: |
          ./project/generate-maintainers-file.py community
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          title: Update maintainers file
          signoff: true
